// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdUMo6zgpPzWTUBnRc9OSGALCzgGSezEg',
    appId: '1:632276317104:android:e9ae6d99acd98699b2dc75',
    messagingSenderId: '632276317104',
    projectId: 'mynotes-oshoora1',
    storageBucket: 'mynotes-oshoora1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6J1soFsaL8ce42XqZg-cr-NpMT5w_c7U',
    appId: '1:632276317104:ios:81819cd79e5abf07b2dc75',
    messagingSenderId: '632276317104',
    projectId: 'mynotes-oshoora1',
    storageBucket: 'mynotes-oshoora1.appspot.com',
    iosBundleId: 'com.oshoora.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxnwFUhw8MkLTofe0EkyAAk2quhWR9CDA',
    appId: '1:632276317104:web:87f7fc98a27dfb28b2dc75',
    messagingSenderId: '632276317104',
    projectId: 'mynotes-oshoora1',
    authDomain: 'mynotes-oshoora1.firebaseapp.com',
    storageBucket: 'mynotes-oshoora1.appspot.com',
  );
}
